spring:
  profiles:
    active: ${spring.profiles.active}
#  task:
#    execution:
#      thread-name-prefix: imooc-qinyi-task-
#      pool:
#        core-size: 2
#        max-size: 8
#  task:
#    scheduling:
#      pool:
#        size: 5
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc_escape?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 20
#      idle-timeout: 500000
#      max-lifetime: 540000
#      connection-timeout: 60000
#      connection-test-query: SELECT 1
#      pool-name: SpringEscapeHikariPool
#  jackson:
#  #参数意义：
#  #JsonInclude.Include.ALWAYS       默认
#  #JsonInclude.Include.NON_DEFAULT   属性为默认值不序列化
#  #JsonInclude.Include.NON_EMPTY     属性为 空（””） 或者为 NULL 都不序列化
#  #JsonInclude.Include.NON_NULL      属性为NULL  不序列化
#    default-property-inclusion: ALWAYS
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss